import type { Listing } from "@/lib/domain/types";

const PHOTO =
  "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=800&auto=format&fit=crop";

/** Demo listings mirroring the reference HTML — used only when Supabase is unavailable in development. */
export const DEMO_STANZE_LISTINGS: Listing[] = [
  {
    id: "demo-1",
    propertyId: "dp-1",
    title: "Singola luminosa",
    cityLabel: "Ancona",
    neighbourhood: "Torrette",
    monthlyRent: 380,
    utilitiesEstimate: 0,
    deposit: 380,
    contractType: "stanza_singola",
    availableFrom: "2026-09-01",
    roomTypeLabel: "Singola",
    furnished: true,
    privateBathroom: true,
    amenities: ["Wifi", "Lavatrice"],
    photoUrls: [PHOTO],
    hasRealPhoto: true,
    landlordVerified: true,
    guaranteedRent: true,
    propertyStatus: "attivo",
    sizeSqm: 14,
    hasBalcony: false,
    hasElevator: false,
    flatmatesCount: 2,
    roomType: "singola",
    heatingType: "autonomo",
    minContractMonths: 6,
    petsAllowed: false,
    smokingAllowed: false,
    createdAt: "2026-03-01T00:00:00Z",
    atmosphereTags: ["Bagno privato", "Arredata", "Wifi"],
  },
  {
    id: "demo-2",
    propertyId: "dp-2",
    title: "Doppia in centro",
    cityLabel: "Ancona",
    neighbourhood: "Centro",
    monthlyRent: 320,
    utilitiesEstimate: 0,
    deposit: null,
    contractType: "stanza_doppia",
    availableFrom: "2026-08-01",
    roomTypeLabel: "Doppia",
    furnished: true,
    privateBathroom: false,
    amenities: ["Lavatrice", "Riscaldamento centralizzato"],
    photoUrls: [PHOTO],
    hasRealPhoto: true,
    landlordVerified: false,
    guaranteedRent: false,
    propertyStatus: "attivo",
    sizeSqm: 11,
    hasBalcony: false,
    hasElevator: false,
    flatmatesCount: 3,
    roomType: "doppia",
    heatingType: "centralizzato",
    minContractMonths: 12,
    petsAllowed: false,
    smokingAllowed: false,
    createdAt: "2026-04-01T00:00:00Z",
    atmosphereTags: ["Arredata", "Spese incluse"],
  },
  {
    id: "demo-3",
    propertyId: "dp-3",
    title: "Doppia uso singola",
    cityLabel: "Ancona",
    neighbourhood: "Centro / Villarey",
    monthlyRent: 420,
    utilitiesEstimate: 40,
    deposit: 420,
    contractType: "stanza_doppia",
    availableFrom: "2026-09-15",
    roomTypeLabel: "Doppia uso singola",
    furnished: false,
    privateBathroom: true,
    amenities: ["Aria condizionata"],
    photoUrls: [PHOTO],
    hasRealPhoto: true,
    landlordVerified: true,
    guaranteedRent: false,
    propertyStatus: "attivo",
    sizeSqm: 20,
    hasBalcony: true,
    hasElevator: false,
    flatmatesCount: 1,
    roomType: "dus",
    heatingType: "autonomo",
    minContractMonths: 6,
    petsAllowed: false,
    smokingAllowed: false,
    createdAt: "2026-05-01T00:00:00Z",
    atmosphereTags: ["Balcone", "Aria cond."],
  },
  {
    id: "demo-4",
    propertyId: "dp-4",
    title: "Singola Palombina",
    cityLabel: "Ancona",
    neighbourhood: "Palombina",
    monthlyRent: 350,
    utilitiesEstimate: 25,
    deposit: 350,
    contractType: "stanza_singola",
    availableFrom: null,
    roomTypeLabel: "Singola",
    furnished: true,
    privateBathroom: false,
    amenities: ["Wifi"],
    photoUrls: [PHOTO],
    hasRealPhoto: true,
    landlordVerified: true,
    guaranteedRent: true,
    propertyStatus: "attivo",
    sizeSqm: 15,
    hasBalcony: false,
    hasElevator: true,
    flatmatesCount: 2,
    roomType: "singola",
    heatingType: "autonomo",
    minContractMonths: 12,
    petsAllowed: true,
    smokingAllowed: false,
    createdAt: "2026-02-15T00:00:00Z",
    atmosphereTags: ["Ascensore", "Arredata"],
  },
  {
    id: "demo-5",
    propertyId: "dp-5",
    title: "Doppia Torrette",
    cityLabel: "Ancona",
    neighbourhood: "Torrette",
    monthlyRent: 290,
    utilitiesEstimate: 20,
    deposit: null,
    contractType: "stanza_doppia",
    availableFrom: "2026-09-01",
    roomTypeLabel: "Doppia",
    furnished: false,
    privateBathroom: false,
    amenities: ["Lavatrice", "Riscaldamento centralizzato"],
    photoUrls: [PHOTO],
    hasRealPhoto: true,
    landlordVerified: false,
    guaranteedRent: false,
    propertyStatus: "attivo",
    sizeSqm: 10,
    hasBalcony: false,
    hasElevator: false,
    flatmatesCount: 3,
    roomType: "doppia",
    heatingType: "centralizzato",
    minContractMonths: 6,
    petsAllowed: false,
    smokingAllowed: false,
    createdAt: "2026-06-01T00:00:00Z",
    atmosphereTags: ["Lavatrice"],
  },
  {
    id: "demo-6",
    propertyId: "dp-6",
    title: "Singola con balcone",
    cityLabel: "Ancona",
    neighbourhood: "Centro",
    monthlyRent: 450,
    utilitiesEstimate: 35,
    deposit: 450,
    contractType: "stanza_singola",
    availableFrom: "2026-07-01",
    roomTypeLabel: "Singola",
    furnished: true,
    privateBathroom: true,
    amenities: ["Wifi", "Aria condizionata"],
    photoUrls: [PHOTO],
    hasRealPhoto: true,
    landlordVerified: true,
    guaranteedRent: false,
    propertyStatus: "attivo",
    sizeSqm: 22,
    hasBalcony: true,
    hasElevator: true,
    flatmatesCount: 1,
    roomType: "singola",
    heatingType: "autonomo",
    minContractMonths: 12,
    petsAllowed: false,
    smokingAllowed: false,
    createdAt: "2026-01-20T00:00:00Z",
    atmosphereTags: ["Bagno privato", "Balcone"],
  },
  {
    id: "demo-7",
    propertyId: "dp-7",
    title: "DUS Palombina",
    cityLabel: "Ancona",
    neighbourhood: "Palombina",
    monthlyRent: 310,
    utilitiesEstimate: 0,
    deposit: 310,
    contractType: "stanza_doppia",
    availableFrom: "2026-09-10",
    roomTypeLabel: "Doppia uso singola",
    furnished: true,
    privateBathroom: false,
    amenities: ["Wifi"],
    photoUrls: [PHOTO],
    hasRealPhoto: true,
    landlordVerified: false,
    guaranteedRent: true,
    propertyStatus: "attivo",
    sizeSqm: 16,
    hasBalcony: false,
    hasElevator: false,
    flatmatesCount: 2,
    roomType: "dus",
    heatingType: "autonomo",
    minContractMonths: 6,
    petsAllowed: false,
    smokingAllowed: true,
    createdAt: "2026-03-20T00:00:00Z",
    atmosphereTags: ["Arredata"],
  },
  {
    id: "demo-8",
    propertyId: "dp-8",
    title: "Singola Torrette bagno privato",
    cityLabel: "Ancona",
    neighbourhood: "Torrette",
    monthlyRent: 400,
    utilitiesEstimate: 30,
    deposit: 400,
    contractType: "stanza_singola",
    availableFrom: null,
    roomTypeLabel: "Singola",
    furnished: false,
    privateBathroom: true,
    amenities: ["Wifi", "Lavatrice", "Aria condizionata", "Riscaldamento centralizzato"],
    photoUrls: [PHOTO],
    hasRealPhoto: true,
    landlordVerified: true,
    guaranteedRent: false,
    propertyStatus: "attivo",
    sizeSqm: 13,
    hasBalcony: false,
    hasElevator: false,
    flatmatesCount: 2,
    roomType: "singola",
    heatingType: "centralizzato",
    minContractMonths: 12,
    petsAllowed: false,
    smokingAllowed: false,
    createdAt: "2026-07-01T00:00:00Z",
    atmosphereTags: ["Bagno privato", "Lavatrice"],
  },
];
