import type { Room } from "./types";

/** Dati di esempio — da rimuovere in produzione quando Supabase è attivo. */
export const MOCK_ROOMS: Room[] = [
  {
    id: "room-1",
    title: "Camera luminosa vicino a Navigli",
    city: "Milano",
    neighborhood: "Navigli",
    rentMonthly: 680,
    availableFrom: "2026-09-01",
    beds: 1,
    amenities: ["wifi", "lavanderia", "balcone"],
    lifestyleTags: ["sociale", "aperitivo", "studenti"],
    cleanliness: 4,
    noiseLevel: 3,
    petsAllowed: false,
    smokingAllowed: false,
    description:
      "Stanza in appartamento condiviso con due coinquilini. Cucina attrezzata e zona living ampia.",
  },
  {
    id: "room-2",
    title: "Quiet room in Isola",
    city: "Milano",
    neighborhood: "Isola",
    rentMonthly: 750,
    availableFrom: "2026-08-15",
    beds: 1,
    amenities: ["wifi", "scrivania", "aria-condizionata"],
    lifestyleTags: ["tranquillo", "remote-work", "ordinato"],
    cleanliness: 5,
    noiseLevel: 1,
    petsAllowed: true,
    smokingAllowed: false,
    description:
      "Ideale per chi lavora da remoto. Casa ordinata, regole chiare, coinquilini rispettosi.",
  },
  {
    id: "room-3",
    title: "Doppia in zona Università",
    city: "Milano",
    neighborhood: "Città Studi",
    rentMonthly: 520,
    availableFrom: "2026-10-01",
    beds: 2,
    amenities: ["wifi", "armadio", "bicicletta"],
    lifestyleTags: ["studenti", "economico", "sociale"],
    cleanliness: 3,
    noiseLevel: 3,
    petsAllowed: false,
    smokingAllowed: false,
    description:
      "Camera doppia a due passi dal Politecnico. Atmosfera giovane e conviviale.",
  },
  {
    id: "room-4",
    title: "Stanza con terrazzo a Porta Romana",
    city: "Milano",
    neighborhood: "Porta Romana",
    rentMonthly: 820,
    availableFrom: "2026-09-10",
    beds: 1,
    amenities: ["wifi", "terrazzo", "lavastoviglie"],
    lifestyleTags: ["design", "tranquillo", "foodie"],
    cleanliness: 5,
    noiseLevel: 2,
    petsAllowed: true,
    smokingAllowed: false,
    description:
      "Appartamento curato, terrazzo condiviso e ottima esposizione. Preferenza per profili ordinati.",
  },
  {
    id: "room-5",
    title: "Camera economica a Bovisa",
    city: "Milano",
    neighborhood: "Bovisa",
    rentMonthly: 450,
    availableFrom: "2026-08-20",
    beds: 1,
    amenities: ["wifi", "riscaldamento"],
    lifestyleTags: ["economico", "studenti", "essenziale"],
    cleanliness: 3,
    noiseLevel: 2,
    petsAllowed: false,
    smokingAllowed: true,
    description:
      "Soluzione pratica vicino al campus Bovisa. Spazi essenziali, affitto contenuto.",
  },
];
